# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89eee31db50f33d864e4850e083190ee43f658ec520b9293e94e2c95e54ceeefc5c32ac16b2ee69e71db08f8e40b3e5639e70c5a965b583ee337c7e449c32503

test:
  secret_key_base: 5e34779ed47cc8bcd091b3fe97d6215b2675153aef8296cd12f7a732f2f5512ddb426cb31d35395f0896d289284c123f98521666ac772092032a3cc24a617ab0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
